### PR TITLE
Tesla engine v motor

### PR DESCRIPTION
**Pull request by amancevice**
I think it's more correct to say "Tesla makes computers with wheels and **motors**."  I'll concede they're somewhat interchangeable, however.

[citation (stackexchange.com)](http://english.stackexchange.com/questions/42027/semantic-difference-between-engine-and-motor)
[citation (mit.edu)](http://engineering.mit.edu/ask/what%E2%80%99s-difference-between-motor-and-engine)

### CODE REVIEW

**Comment by a1k0n** [comment]
Ha, I noticed that too. Agreed.

**Comment by willbuck** [comment]
I also thought this when I read the article, gj submitting a PR for it

**Comment by tophtucker** [comment]
This is super nerdy pedantic and looks to be correct. :) Checking with @JimAley and @ftrain.

**Comment by amancevice** [comment]
closing as an orphan

**Pull request closed without merging**
