### PR TITLE
npm does not stand for "node package manager"

### PR DESCRIPTION
**Pull request by seldo**
It is also not capitalized :-)

I loved this article. An epic poem for the internet age.

### CODE REVIEW

**Comment by vitorgalvao** [comment]
To be more accurate, npm isn’t “the package manager for Node.js”, but “a package manager for JavaScript”. There is nothing tying it to Node.js, and it can be (and is) used in other contexts (which they prominently show o the top of [the website](https://www.npmjs.com/)). Node.js uses npm by default as a package manager, but other than that they don’t have a much deeper link.

**Comment by Khobalt** [comment]
Read the first [readme for npm](https://github.com/npm/npm/blob/344649dd145ab331a5ff7a2032c100ca62dc1227/README.md) and I think you'll agree they are quite deeply linked. Even if the projects have diverged, "node package manager" is totally accurate, if not up to date.

**Comment by vitorgalvao** [comment]
> totally accurate, if not up to date.

You’re arguing a definition is valid today because it was valid in the past. That makes absolutely no sense.

[Straight from npm’s lead](https://github.com/Homebrew/homebrew/pull/35853#issuecomment-70554441):

> we draw no distinction between joyent/node and iojs/io.js. We support them both equally. npm, Inc. is not using iojs in production -- yet -- but if iojs users encounter difficulties using npm with iojs, we will treat them as seriously as issues using npm with node.

npm is the package manager Node.js uses, it is not Node.js’s package manager; it does not serve them. That wording and definition is limiting, and implies npm is useful because of and perhaps even dependent on Node.js, which is absolutely false. Even if it were true in the past, that is absolutely irrelevant now, and for the article. If at one point in time [ed](https://en.wikipedia.org/wiki/Ed_(text_editor)) billed itself as the best way to edit text and it was true<sup>1</sup>, that no longer holds true today.

I’ll say it again: if the projects took different routes they are different things, and they’re history bears no relevant to this particular sentence. npm is, as of today, not simply Node.js’s package manager, which makes this sentence, written in the present tense, inaccurate.

---

<sup>1</sup> Not saying it did r it was, merely making a point.

**Comment by blinsay** [comment]
It's actually not a package manager at all. [NPM stands for Node Package Maid](https://medium.com/cool-code-pal/how-node-js-is-going-to-replace-javascript-cf72b588b1b).

**Comment by seldo** [comment]
@vitorgalvao: it is both *the* package manager for node.js and *a* package manager for JavaScript (I wrote the copy for the website, but feel like "the" package manager for JavaScript is perhaps getting ahead of reality a little bit).

Either way, in this context I thought the former was more relevant :-)

**Comment by vitorgalvao** [comment]
> but feel like "the" package manager for JavaScript is perhaps getting ahead of reality a little bit

Which is why I called it, in the first reply, *a* package manager for JavaScript.

I also started by saying “to be more accurate”. I do not think your current definition is wrong, just that it should be broader and more complete by not limiting the definition to Node.js.

**Comment by seldo** [comment]
In the context, the point of the sentence is not to fully define the scope of npm and its exact definition. It's to introduce npm and explain why it's relevant to the non-technical person reading the article.

**Comment by vitorgalvao** [comment]
Which both definitions do, with the exact same amount of words, and none of them being simpler to understand than the other. Given that, there is absolutely no reason to not use the more correct, broader, definition. It’s not like we’re talking about explaining the whole backstory, here, *both definitions are correct and simple, but one of them is more accurate*.

**Comment by seldo** [comment]
Okay. How about "as the CTO of npm, Inc., I think it's less confusing if our product was described in this context as the package manager for node.js rather than introducing its (more accurate, but not relevant) role as a package manager for javascript"?

**Comment by vitorgalvao** [comment]
> How about "as the CTO of npm, Inc.

[Your position is irrelevant to the matter, and gives you no special powers](https://en.wikipedia.org/wiki/Argument_from_authority).

> I think

Expressing your opinion, though, is perfectly valid.

> it's less confusing

It’s there we disagree. You spoke about non-technical people before. Most people I know are non-technical; some know what JavaScript is, none has any clue what Node.js is.

It is clear we won’t reach an agreement, though. We both made our points, so whoever is in charge of making the change has enough information to make a decision.

**Comment by ftrain** [comment]
chwwwslwsaaxg4k

**Comment by nathanielksmith** [comment]
lol

**Comment by ftrain** [comment]
OH BUT WAIT THE PLOT THICKENS https://github.com/npm/npm/commit/226a6776a1a9e28570485623b8adc2ec4b041335#diff-0743750f368afcb1060491fc9755e3d8

**Comment by HugoGiraudel** [comment]
This thread is getting better and better. :)

**Comment by ftrain** [comment]
One idea: We could wait until mid or late 2016 to let things settle down, then decide on the best course of action.

**Comment by seldo** [comment]
I am deeply sorry I got involved in the first place. There's your metaphor for open-source participation, Paul.

**Comment by mcdonnelldean** [comment]
... mumble, mumble... ECMAScript... mumble... should be epm by rights... mumble...

**Comment by regularmike** [comment]
"Node package manager" is just one of many ridiculous and non-sensical made-up expansions of npm. What would that even mean???

**Comment by disusered** [comment]
A person who works for npm submits a PR with the updated name, which the author corroborates himself with a pull request from 6 months ago. Instead of following through given the request and backing evidence, the request is refused and the author uses his tens of thousands of followers on Twitter to mock the request and the requester.

Looking at other pull requests, we can find similar requests for PHP [1](https://github.com/BloombergMedia/whatiscode/pull/6)[2](https://github.com/BloombergMedia/whatiscode/issues/49), acknowledged by the top contributor to this project. Somehow, that one was able to make it twice without leading to a public spectacle.

What's the point of putting this on GitHub if traditional journalistic measures would have worked better, ie npm has a rep contact the publisher because they published the wrong name?

**Comment by mcdonnelldean** [comment]
@disusered I'm operating on the assumption they are ribbing each other. Joking aside I think @seldo's change is correct for the target audience. While it may be used for other things, npm is first and foremost, a package manager for Node.js

**Comment by disusered** [comment]
As an outsider not privy to insider jokes, the message being broadcast is very negative and not conducive towards collaboration.

**Comment by vielmetti** [comment]
It was simpler when we were arguing about the name of the Pathologically Eclectic Rubbish Lister.

**Comment by regularmike** [comment]
After we sort this out we can set everyone straight on how to pronounce "OS X."

**Comment by nisaacson** [comment]
@regularmike 

```sh
say "OS X"
```

**Comment by regularmike** [comment]
utter "OS X"

**Comment by drewlustro** [comment]
epic thread is epic :100: 

:8ball: OS X is pronounced "Auss Ex".

**Comment by farrukhsubhani** [comment]
OS X has OS silent.

**Comment by revhazroot** [comment]
This thread right now

**Comment by tomprince** [comment]
While `npm` may no longer stand for "Node Package Manager", that is the origin of the name. I think removing that connection makes the text weaker.

**Comment by seldo** [comment]
\o/

**Pull request closed without merging**
