### PR TITLE
Update 'Productivity Enhancers' copy to include Vim/Emacs over Brackets/TextWrangler

### PR DESCRIPTION
**Pull request by noahsark769**
First of all, fantastic article! Really great intro to the world of software development. Read the whole thing, and just thought I would try to contribute a bit.

Brackets and TextWrangler are usually not widely used enough to justify being called "favorites", whereas I think Vim and Emacs would certainly capture that title. I tried to do some actual research on what text editors actually have the most adoption, but I could hardly find any studies or blog posts. [This post](http://www.sitepoint.com/editor-rubyists-use/) is admittedly Ruby specific, but shows Vim, Emacs, and Sublime as the top spots, which is what I would have guessed off the top of my head. So, I updated the copy to include Vim and Emacs.

If the author feels that TextWrangler/Brackets would be better then feel free to close this, but I figured that Vim and Emacs probably deserve a spot in the answer to "What is code?" :)

### CODE REVIEW

**Comment by vcavallo** [comment]
I, too, felt a pang of sadness at the lack of mention of vim or emacs in that spot. I quickly told myself not to be an editor-"prosthelytizer", but I can't help feel that this mind-blowingly wonderful overview of this entire industry is woefully lacking a mention of vim (or emacs I guess) :)

**Comment by noahsark769** [comment]
Looks like this isn't going to get merged - I'm going to close it to clean up my open PR dashboard :)

**Comment by 1wheel** [comment]
@ftrain used org mode for the first draft of this; he's teasing y'all a little here. 

https://github.com/BloombergMedia/whatiscode/blob/39fd8e6c521931cd92854b5c35820a1bdc27274b/research/README.md

**Comment by noahsark769** [comment]
Hah, nice! Let me just say though, Sublime ftw 💯

**Pull request closed without merging**
